#!/usr/bin/env bash
# create-pr.sh
# ─────────────────────────────────────────────────────────────────────────────
# Creates a Git commit and opens a pull request via the GitHub API.
# All communication uses curl only (zero external dependencies).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utils.sh
source "$SCRIPT_DIR/utils.sh"

create_pr() {
  local ws="${WORKSPACE:?WORKSPACE must be set}"
  local branch="${PR_BRANCH:-copilot/unify-repo}"
  local message="${COMMIT_MESSAGE:-chore: apply unify-repo enrichment}"
  local repo="${GITHUB_REPOSITORY:-}"
  local default_branch="${GITHUB_REF_NAME:-main}"

  if [[ -z "$repo" ]]; then
    log_warn "GITHUB_REPOSITORY not set — skipping PR creation"
    return 0
  fi
  if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    log_warn "GITHUB_TOKEN not set — skipping PR creation"
    return 0
  fi

  log_step "Creating pull request"

  # ── Configure git identity ─────────────────────────────────────────────────
  git -C "$ws" config user.email "unify-repo[bot]@users.noreply.github.com" || true
  git -C "$ws" config user.name  "unify-repo[bot]" || true

  # ── Create / reset the PR branch ─────────────────────────────────────────
  git -C "$ws" checkout -B "$branch" 2>/dev/null || {
    log_error "Failed to create branch $branch"
    return 1
  }

  # ── Stage and commit all changes ──────────────────────────────────────────
  git -C "$ws" add -A
  if git -C "$ws" diff --cached --quiet; then
    log_info "Nothing to commit — no PR needed"
    echo "changes-made=false" >> "${GITHUB_OUTPUT:-/dev/null}"
    return 0
  fi

  git -C "$ws" commit -m "$message" \
    -m "Generated by the [unify-repo](https://github.com/ReZonArc/gh-action-unify-repo) action."
  log_ok "Committed changes on branch $branch"

  # ── Push the branch ───────────────────────────────────────────────────────
  local remote_url="${GITHUB_SERVER_URL:-https://github.com}/${repo}.git"
  git -C "$ws" push --force-with-lease \
    "https://x-access-token:${GITHUB_TOKEN}@${remote_url#https://}" \
    "HEAD:refs/heads/${branch}" 2>&1 | sed 's/x-access-token:[^@]*/x-access-token:***/g'
  log_ok "Pushed $branch"

  # ── Open (or update) the PR via GitHub REST API ───────────────────────────
  local pr_title="chore: unify-repo enrichment"
  local pr_body
  pr_body=$(cat <<'PRBODY'
## Unify-Repo Enrichment

This pull request was automatically generated by the
[unify-repo](https://github.com/ReZonArc/gh-action-unify-repo) GitHub Action.

### What was changed

| File | Description |
|------|-------------|
| `CODEBASE.md` | Codebase structure, technologies, and directory tree |
| `INTEGRATION_PLAN.md` | Phased road-map for integrating all components |
| `TEST_COVERAGE_GUIDE.md` | Test-coverage targets and next steps |
| `.github/workflows/build.yml` | Comprehensive CI for all detected components |
| `tests/` or `spec/` | Scaffolded test files for uncovered source files |

### Review notes

- All generated files include clear `TODO` markers for human follow-up.
- The CI workflow is tailored to the detected technology stack.
- No existing files were overwritten (unless `overwrite: true` was set).

> Re-run the action with `overwrite: true` to refresh all generated files.
PRBODY
)

  local payload; payload=$(python3 -c "
import json, sys
print(json.dumps({
  'title': sys.argv[1],
  'body':  sys.argv[2],
  'head':  sys.argv[3],
  'base':  sys.argv[4],
  'draft': False,
}))" "$pr_title" "$pr_body" "$branch" "$default_branch")

  local response; response=$(gh_api POST "/repos/${repo}/pulls" "$payload" 2>&1 || true)
  local pr_url; pr_url=$(echo "$response" | python3 -c \
    "import json,sys; d=json.load(sys.stdin); print(d.get('html_url',''))" 2>/dev/null || true)

  if [[ -n "$pr_url" && "$pr_url" != *"Unprocessable"* ]]; then
    log_ok "Pull request created: $pr_url"
    echo "pr-url=${pr_url}"     >> "${GITHUB_OUTPUT:-/dev/null}"
    echo "changes-made=true"    >> "${GITHUB_OUTPUT:-/dev/null}"
  else
    # PR may already exist — try to get its URL
    local existing; existing=$(gh_api GET \
      "/repos/${repo}/pulls?head=${repo%/*}:${branch}&state=open" 2>/dev/null || true)
    local existing_url; existing_url=$(echo "$existing" | python3 -c \
      "import json,sys; arr=json.load(sys.stdin); print(arr[0]['html_url'] if arr else '')" \
      2>/dev/null || true)
    if [[ -n "$existing_url" ]]; then
      log_ok "Pull request already exists: $existing_url"
      echo "pr-url=${existing_url}" >> "${GITHUB_OUTPUT:-/dev/null}"
    else
      log_warn "Could not create or find PR. Response: $response"
    fi
    echo "changes-made=true" >> "${GITHUB_OUTPUT:-/dev/null}"
  fi
}

# Run when executed directly
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  create_pr
fi
