#!/usr/bin/env bash
# main.sh
# ─────────────────────────────────────────────────────────────────────────────
# Orchestrator: reads environment variables set by action.yml and runs the
# requested enrichment steps in order.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utils.sh
source "$SCRIPT_DIR/utils.sh"

# ── Validate required inputs ─────────────────────────────────────────────────
: "${WORKSPACE:?WORKSPACE environment variable must be set}"
: "${ENRICHMENT_STEPS:=explain,tests,plan}"
: "${CREATE_PR:=true}"
: "${PR_BRANCH:=copilot/unify-repo}"
: "${COMMIT_MESSAGE:=chore: apply unify-repo enrichment}"
: "${OVERWRITE:=false}"

log_step "unify-repo · Starting enrichment"
log_info "Workspace  : $WORKSPACE"
log_info "Steps      : $ENRICHMENT_STEPS"
log_info "Create PR  : $CREATE_PR"
log_info "Overwrite  : $OVERWRITE"

# Export everything so child scripts can pick it up
export WORKSPACE ENRICHMENT_STEPS CREATE_PR PR_BRANCH COMMIT_MESSAGE OVERWRITE

REPORT_PATH="$WORKSPACE/ENRICHMENT_REPORT.md"

# ── Run steps ────────────────────────────────────────────────────────────────
_run_if_requested() {
  local step="$1"
  local script="$2"
  if echo "$ENRICHMENT_STEPS" | tr ',' '\n' | grep -qx "$step"; then
    bash "$SCRIPT_DIR/$script"
  else
    log_skip "Step '$step' not in requested steps ($ENRICHMENT_STEPS)"
  fi
}

_run_if_requested "explain" "step1-explain-organize.sh"
_run_if_requested "tests"   "step2-analyze-tests.sh"
_run_if_requested "plan"    "step3-integration-plan.sh"

# ── Write enrichment report ───────────────────────────────────────────────────
log_step "Writing enrichment report"

declare -a generated_files=()
[[ -f "$WORKSPACE/CODEBASE.md"           ]] && generated_files+=("CODEBASE.md")
[[ -f "$WORKSPACE/TEST_COVERAGE_GUIDE.md" ]] && generated_files+=("TEST_COVERAGE_GUIDE.md")
[[ -f "$WORKSPACE/INTEGRATION_PLAN.md"  ]] && generated_files+=("INTEGRATION_PLAN.md")
[[ -f "$WORKSPACE/.github/workflows/build.yml" ]] && generated_files+=(".github/workflows/build.yml")

# Collect newly scaffolded test files
while IFS= read -r tf; do
  generated_files+=("$(relative_path "$WORKSPACE" "$tf")")
done < <(git -C "$WORKSPACE" status --porcelain 2>/dev/null | \
           grep '^[?A]' | awk '{print $2}' | \
           grep -E '(test|spec)' | head -30 || true)

cat > "$REPORT_PATH" <<RDEOF
# Enrichment Report

> Generated by [unify-repo](https://github.com/ReZonArc/gh-action-unify-repo) on $(timestamp)

## Steps executed

$(echo "$ENRICHMENT_STEPS" | tr ',' '\n' | while read -r s; do
    case "$s" in
      explain) echo "- ✅ **Explain & Organize** — CODEBASE.md, .github aggregation, build CI" ;;
      tests)   echo "- ✅ **Test Coverage** — scaffolded test files, coverage config, guide" ;;
      plan)    echo "- ✅ **Integration Plan** — INTEGRATION_PLAN.md with phased road-map" ;;
      *)       echo "- ⚠️  Unknown step: $s" ;;
    esac
  done)

## Files generated / modified

$(for f in "${generated_files[@]:-}"; do
    [[ -z "$f" ]] && continue
    echo "| \`$f\` |"
  done | head -50)

## Next steps

1. Review each generated file and fill in the \`TODO\` markers.
2. Run the test suite and check coverage reports.
3. Follow the phases in \`INTEGRATION_PLAN.md\`.
4. Merge the PR and enable branch protection.

---
_Re-run this action with \`overwrite: true\` to regenerate all files._
RDEOF

log_ok "Written: ENRICHMENT_REPORT.md"

# ── Set action outputs ────────────────────────────────────────────────────────
if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  echo "report-path=ENRICHMENT_REPORT.md" >> "$GITHUB_OUTPUT"
fi

# ── Create PR if requested ────────────────────────────────────────────────────
if [[ "$CREATE_PR" == "true" ]]; then
  bash "$SCRIPT_DIR/create-pr.sh"
else
  # Still report whether changes were made
  if git -C "$WORKSPACE" status --porcelain 2>/dev/null | grep -q .; then
    [[ -n "${GITHUB_OUTPUT:-}" ]] && echo "changes-made=true" >> "$GITHUB_OUTPUT"
    log_info "Changes are present in the workspace (create-pr=false, not committed)"
  else
    [[ -n "${GITHUB_OUTPUT:-}" ]] && echo "changes-made=false" >> "$GITHUB_OUTPUT"
    log_info "No changes detected in workspace"
  fi
fi

log_step "unify-repo · Enrichment complete 🎉"
