#!/usr/bin/env bash
# step1-explain-organize.sh
# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Explain & Organize
#   • Scans the codebase and writes CODEBASE.md
#   • Aggregates nested .github sub-directories into the workspace root
#   • Updates path references inside workflow files
#   • Generates a comprehensive CI workflow (.github/workflows/build.yml)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utils.sh
source "$SCRIPT_DIR/utils.sh"

# ── Entry point ──────────────────────────────────────────────────────────────
run_step1() {
  local ws="${WORKSPACE:?WORKSPACE must be set}"
  local overwrite="${OVERWRITE:-false}"

  log_step "Step 1 · Explain & Organize"

  local stack; stack=$(detect_stack "$ws")
  log_info "Detected stack: $stack"

  _write_codebase_md  "$ws" "$stack" "$overwrite"
  _aggregate_github   "$ws"
  _update_workflow_refs "$ws"
  _generate_build_ci  "$ws" "$stack" "$overwrite"
}

# ── 1a. CODEBASE.md ──────────────────────────────────────────────────────────
_write_codebase_md() {
  local ws="$1" stack="$2" overwrite="$3"
  local out="$ws/CODEBASE.md"

  if ! should_write "$out" "$overwrite"; then
    log_skip "CODEBASE.md already exists (set overwrite=true to replace)"
    return
  fi

  log_info "Writing CODEBASE.md …"

  # Collect stats
  local total_files; total_files=$(find "$ws" -type f ! -path "*/.git/*" \
    ! -path "*/node_modules/*" ! -path "*/.venv/*" ! -path "*/vendor/*" \
    2>/dev/null | wc -l | tr -d ' ')

  local total_dirs; total_dirs=$(find "$ws" -type d ! -path "*/.git/*" \
    ! -path "*/node_modules/*" ! -path "*/.venv/*" ! -path "*/vendor/*" \
    2>/dev/null | wc -l | tr -d ' ')

  local ext_counts; ext_counts=$(count_files_by_extension "$ws")

  local tree_output; tree_output=$(generate_tree "$ws" "" 4 0)

  # Identify entry-point candidates
  local entry_points=()
  for ep in main.go main.py app.py manage.py index.js index.ts src/index.ts \
            src/main.ts src/main.js src/app.ts src/app.js Program.cs; do
    [[ -f "$ws/$ep" ]] && entry_points+=("\`$ep\`")
  done
  [[ ${#entry_points[@]} -eq 0 ]] && entry_points+=("_none detected_")

  # Key config files
  local configs=()
  for cfg in package.json tsconfig.json pyproject.toml setup.cfg requirements.txt \
             Pipfile pom.xml build.gradle go.mod Cargo.toml Gemfile composer.json \
             Dockerfile docker-compose.yml .env.example; do
    [[ -f "$ws/$cfg" ]] && configs+=("\`$cfg\`")
  done
  [[ ${#configs[@]} -eq 0 ]] && configs+=("_none detected_")

  cat > "$out" <<MDEOF
# Codebase Overview

> Generated by [unify-repo](https://github.com/ReZonArc/gh-action-unify-repo) on $(timestamp)

## Summary

| Metric | Value |
|--------|-------|
| Total files | ${total_files} |
| Total directories | ${total_dirs} |
| Detected stack | \`${stack}\` |

## Key Technologies

$(for t in $stack; do echo "- **${t}**"; done)

## Entry Points

$(for ep in "${entry_points[@]}"; do echo "- $ep"; done)

## Configuration Files

$(for cfg in "${configs[@]}"; do echo "- $cfg"; done)

## File Distribution by Extension

\`\`\`
${ext_counts:-N/A}
\`\`\`

## Directory Tree

\`\`\`
$(basename "$ws")/
${tree_output}
\`\`\`

## Code Organization

$(if echo "$stack" | grep -q nodejs; then cat <<'NODEJS'
The project follows a **Node.js** layout. Source code lives under `src/` (or the
project root), tests in `__tests__/` or alongside source files with a `.test.ts`
/ `.spec.ts` suffix, and build artefacts are emitted to `dist/` or `build/`.
NODEJS
fi)
$(if echo "$stack" | grep -q python; then cat <<'PYTH'
The project follows a **Python** layout. Package code is typically found in the
top-level package directory (same name as the project), tests under `tests/`, and
configuration in `pyproject.toml` / `setup.cfg`.
PYTH
fi)
$(if echo "$stack" | grep -q "java-maven\|java-gradle"; then cat <<'JAVA'
The project follows a **Maven/Gradle** layout.
- `src/main/java/` — production source code
- `src/test/java/` — unit & integration tests
- `src/main/resources/` — non-Java resources
JAVA
fi)
$(if echo "$stack" | grep -q go; then cat <<'GO'
The project follows the idiomatic **Go** module layout.
- Package directories at the root alongside `go.mod`
- `cmd/` — binary entry-points (if present)
- `internal/` — private packages
- `pkg/` — exported packages
GO
fi)
$(if echo "$stack" | grep -q rust; then cat <<'RUST'
The project follows a standard **Rust/Cargo** layout.
- `src/lib.rs` or `src/main.rs` — library or binary root
- `src/bin/` — additional binaries
- `tests/` — integration tests
RUST
fi)

---
_This file is auto-generated. Re-run the [unify-repo](https://github.com/ReZonArc/gh-action-unify-repo)
action to refresh it._
MDEOF

  log_ok "Created CODEBASE.md"
}

# ── 1b. Aggregate nested .github dirs ────────────────────────────────────────
_aggregate_github() {
  local ws="$1"
  local root_github="$ws/.github"

  log_info "Scanning for nested .github directories …"

  local found=0
  while IFS= read -r nested_dir; do
    found=1
    log_info "Merging: $nested_dir  →  $root_github"
    merge_github_dir "$nested_dir" "$root_github"
    # Remove the now-merged nested dir if it is empty
    if [[ -d "$nested_dir" ]] && \
       [[ -z "$(find "$nested_dir" -mindepth 1 -maxdepth 1 2>/dev/null)" ]]; then
      rmdir "$nested_dir"
      log_ok "Removed empty directory: $nested_dir"
    fi
  done < <(find_nested_github_dirs "$ws")

  if [[ $found -eq 0 ]]; then
    log_ok "No nested .github directories found — nothing to merge"
  fi
}

# ── 1c. Update path references in workflow YAML files ────────────────────────
_update_workflow_refs() {
  local ws="$1"
  local workflows_dir="$ws/.github/workflows"

  [[ -d "$workflows_dir" ]] || return 0

  log_info "Checking workflow files for stale path references …"

  while IFS= read -r workflow; do
    # Update references like `subfolder/.github/workflows/` → `.github/workflows/`
    # This handles the most common case where a nested workflow path was hardcoded.
    if grep -qE '\b[^./][^/]*/\.github/' "$workflow" 2>/dev/null; then
      log_info "Updating path references in: $(basename "$workflow")"
      # Replace  `<subdir>/.github/`  with  `.github/`
      sed -i -E 's|[^/"'\''[:space:]]+/\.github/|.github/|g' "$workflow"
      log_ok "Updated: $(basename "$workflow")"
    fi
  done < <(find "$workflows_dir" -name "*.yml" -o -name "*.yaml" 2>/dev/null)
}

# ── 1d. Generate build CI workflow ───────────────────────────────────────────
_generate_build_ci() {
  local ws="$1" stack="$2" overwrite="$3"
  local out="$ws/.github/workflows/build.yml"

  if ! should_write "$out" "$overwrite"; then
    log_skip ".github/workflows/build.yml already exists (set overwrite=true to replace)"
    return
  fi

  mkdir -p "$ws/.github/workflows"
  log_info "Generating .github/workflows/build.yml …"

  # --- Build the job matrix steps based on detected stack --------------------
  local setup_steps="" lint_steps="" test_steps="" build_steps=""

  # Node.js
  if echo "$stack" | grep -q nodejs; then
    local pkg_manager="npm"
    [[ -f "$ws/yarn.lock" ]]     && pkg_manager="yarn"
    [[ -f "$ws/pnpm-lock.yaml" ]] && pkg_manager="pnpm"

    case "$pkg_manager" in
      yarn)
        setup_steps+="
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies (yarn)
        run: yarn install --frozen-lockfile"
        lint_steps+="
      - name: Lint
        run: yarn lint --if-present || true"
        test_steps+="
      - name: Test
        run: yarn test --passWithNoTests --ci || yarn test:ci --passWithNoTests || true"
        build_steps+="
      - name: Build
        run: yarn build --if-present || true"
        ;;
      pnpm)
        setup_steps+="
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile"
        lint_steps+="
      - name: Lint
        run: pnpm run lint --if-present || true"
        test_steps+="
      - name: Test
        run: pnpm test -- --passWithNoTests || true"
        build_steps+="
      - name: Build
        run: pnpm run build --if-present || true"
        ;;
      *)
        setup_steps+="
      - name: Install dependencies (npm)
        run: npm ci --prefer-offline"
        lint_steps+="
      - name: Lint
        run: npm run lint --if-present || true"
        test_steps+="
      - name: Test
        run: npm test -- --passWithNoTests --ci 2>/dev/null || npm run test:ci --if-present || true"
        build_steps+="
      - name: Build
        run: npm run build --if-present || true"
        ;;
    esac
  fi

  # Python
  if echo "$stack" | grep -q python; then
    local py_install="pip install -r requirements.txt"
    [[ -f "$ws/Pipfile" ]]        && py_install="pip install pipenv && pipenv install --dev"
    [[ -f "$ws/pyproject.toml" ]] && py_install="pip install -e '.[dev]' || pip install -e . || pip install -r requirements.txt || true"

    setup_steps+="
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install Python dependencies
        run: $py_install"
    lint_steps+="
      - name: Lint (flake8)
        run: pip install flake8 && flake8 . --max-line-length=120 || true"
    test_steps+="
      - name: Test (pytest)
        run: pip install pytest pytest-cov && pytest --tb=short -q || true"
  fi

  # Java (Maven or Gradle)
  if echo "$stack" | grep -q java-maven; then
    setup_steps+="
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'"
    lint_steps+="
      - name: Checkstyle
        run: mvn checkstyle:check -q || true"
    test_steps+="
      - name: Test (Maven)
        run: mvn test -B"
    build_steps+="
      - name: Build (Maven)
        run: mvn package -B -DskipTests"
  fi

  if echo "$stack" | grep -q java-gradle; then
    setup_steps+="
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'"
    lint_steps+="
      - name: Lint (Gradle)
        run: ./gradlew check --continue -q || true"
    test_steps+="
      - name: Test (Gradle)
        run: ./gradlew test"
    build_steps+="
      - name: Build (Gradle)
        run: ./gradlew build -x test"
  fi

  # Go
  if echo "$stack" | grep -q go; then
    setup_steps+="
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true"
    lint_steps+="
      - name: Vet
        run: go vet ./..."
    test_steps+="
      - name: Test
        run: go test -v -race -coverprofile=coverage.out ./..."
    build_steps+="
      - name: Build
        run: go build ./..."
  fi

  # Rust
  if echo "$stack" | grep -q rust; then
    setup_steps+="
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable"
    lint_steps+="
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings || true"
    test_steps+="
      - name: Test
        run: cargo test --all"
    build_steps+="
      - name: Build
        run: cargo build --release"
  fi

  # .NET
  if echo "$stack" | grep -q dotnet; then
    setup_steps+="
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'"
    lint_steps+="
      - name: Format check
        run: dotnet format --verify-no-changes || true"
    test_steps+="
      - name: Test
        run: dotnet test --no-build --verbosity normal"
    build_steps+="
      - name: Build
        run: dotnet build --configuration Release"
  fi

  # Docker
  local docker_steps=""
  if echo "$stack" | grep -q docker; then
    docker_steps="
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: \${{ github.repository }}:\${{ github.sha }}"
  fi

  # Fallback for generic/shell repos
  if [[ -z "$test_steps" ]]; then
    test_steps="
      - name: Smoke test (shell scripts)
        run: find . -name '*.sh' ! -path '*/.git/*' -exec bash -n {} +"
  fi

  cat > "$out" <<CIEOF
# Comprehensive CI — generated by unify-repo
# Re-run the action to regenerate this file.
name: Build & Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build, lint & test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
${setup_steps}
${lint_steps}
${test_steps}
${build_steps}

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage/
            coverage.out
            htmlcov/
            target/site/jacoco/
          if-no-files-found: ignore
${docker_steps}
CIEOF

  log_ok "Created .github/workflows/build.yml"
}

# Run when executed directly
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  run_step1
fi
